### ISSUE TITLE
sharing / download feature

### ISSUE THREAD

**Issue by doc-sebastian** [ayselafsar/dicomviewer#22]
Good evening,
It would be so useful to have the ability to public share the opened image data directly from your dicomviewer app so that external people can grab the url and directly use your dicom viewer for viewing the shared files (i.e. offering a second medical opinion over the web, etc..).
Thus it would be nice to hide the patient name/data and offer an optional download of the (zipped) dicom data directly from the viewer. It could probably look like this example:

<kbd>![share-view_owner](https://raw.githubusercontent.com/doc-sebastian/dicomviewer/master/screenshots/share-view_owner.jpg)  </kbd>
<kbd>![share-view_sharedview](https://raw.githubusercontent.com/doc-sebastian/dicomviewer/master/screenshots/share-view_sharedview.jpg)  </kbd>

What is your opinion? Do you think it can be implemented without risking security?

**Comment by doc-sebastian** [comment]
Dear Aysel,
Your DicomViewer is sooooo awesome. I recently used it with a big patient MRI dataset of 6Gb and it works like a charm!!! There is only still one thing missing... ;-))

GPXPod has a nice and easy sharing function based on the standard files sharing. It reads the token of shared file/folders from the database and enables sharing via 
https://domain.name/apps/gpxpod/publicFile?token=PZQrKvoZ9GroSio

You can find the code here under "public function publicFile()":
https://gitlab.com/eneiluj/gpxpod-oc/blob/master/controller/pagecontroller.php

Perhaps after adaption only a small share button in the interface targeting to something like
https://domain.name/apps/dicomviewer/publicFile?token=PZQrKvoZ9GroSio
would do the trick.

---
Regarding anonymization: The patient data of a shared URL could be hidden as default. Perhaps adding the correct sharetime (column "stime" in database) as a param to the share URL could be the condition to display the patient data:
https://domain.name/apps/dicomviewer/publicFile?token=PZQrKvoZ9GroSio&stime=1541412101

I wish I could code it on my own :-(
Best regards,
Sebastian

**Comment by ayselafsar** [comment]
Unfortunately, this approach doesn't seem right to me for security reasons, because it isn't enough to hide PHI in display since the non-anonymized DICOM file will still be downloaded and available for the user who is shared with. To achieve this sharing feature, we need to have server-side anonymization and anonymize the shared DICOM file on server before sending it to client. Since we currently have DICOM library in only client, expect users to use Nextcloud sharing feature without anonymization and this isn't in the main scope of this project at the moment, i close this issue as 'wontfix', but if you have any other idea, we can discuss. Thanks.
